import React from "react";
import styled from "styled-components";
import { Container } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faChevronCircleRight,
  faAngleDown,
} from "@fortawesome/free-solid-svg-icons";

const Policy = () => {
  return (
    <StyledContainer>
      <ParagraphWrapper>
        <ParagraphTitle>Privacy Policy</ParagraphTitle>
        <Paragraph>
          Effective date: January 08, 2022 The Alliance for Better Mental Health
          ("us", "we", or "our") operates the https://www.wpatbilisicongress.com
          website (hereinafter referred to as the "Service").
          <br />
          <br />
          This page informs you of our policies regarding the collection, use
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
          <br />
          <br />
          We use your data for your participation in the WPA Thematic Congress
          held in Tbilisi on 14-16 October. By using the Service, you agree to
          the collection and use of information in accordance with this policy.
          Unless otherwise, the terms used in this Privacy Policy have the
          meanings shown below.
        </Paragraph>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} /> <h4>Definitions</h4>
          </UlTitle>
          <UlList>
            <GuideList className="bold">Service</GuideList>
            <Paragraph className="ps-4">
              Service means the https://www.wpatbilisicongress.com website.
            </Paragraph>
            <GuideList className="bold">Personal Data</GuideList>
            <Paragraph className="ps-4">
              Personal Data means data about a living individual who can be
              identified from those data (or from those and other information
              either in our possession or likely to come into our possession).
            </Paragraph>
            <GuideList className="bold">Usage Data</GuideList>
            <Paragraph className="ps-4">
              Usage Data is data collected automatically either generated by the
              use of the Service or from the Service infrastructure itself.
            </Paragraph>
          </UlList>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} />{" "}
            <h4>Information Collection and Use</h4>
          </UlTitle>
          <Paragraph>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you ("Personal Data"). Personally identifiable information
            may include, but is not limited to:
          </Paragraph>
          <UlList>
            <GuideList>First name and last name</GuideList>
            <GuideList>Email address</GuideList>
            <GuideList>Phone number</GuideList>
            <GuideList>Address, Country, City</GuideList>
            <GuideList>Company/Institution name</GuideList>
          </UlList>
          <Paragraph>
            We may use your Personal Data to contact you with issues related to
            the WPA Thematic Congress in Tbilisi.
            <br />
            <br />
            We ask for your personal data to proceed with your registration for
            this Congress and for organising any other services you wish to book
            (i.e. tickets, transfers, restaurant bookings, etc.).
            <br />
            <br />
            Who has access to your personal data? The Congress Secretariat, all
            committees related to the congress (i.e. Organising Committee,
            Scientific Committee, etc.), sponsors and third parties handling
            services related to the congress. Third parties will receive only
            the information required for their operation.
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} /> <h4>Usage Data</h4>
          </UlTitle>
          <Paragraph>
            We may also collect information that your browser sends whenever you
            visit our Service or when you access the Service by or through a
            mobile device ("Usage Data").
            <br />
            <br />
            This Usage Data may include information such as your computer's
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit and other diagnostic data.
            <br />
            <br />
            When you access the Service with a mobile device, this Usage Data
            may include information such as the type of mobile device you use,
            your mobile device unique ID, the IP address of your mobile device,
            your mobile operating system, the type of mobile Internet browser
            you use, unique device identifiers and other diagnostic data.
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} />
            <h4>Disclosure of Data</h4>
          </UlTitle>
          <Paragraph>
            <span>Disclosure for law enforcement</span>
            <br />
            Under certain circumstances, wpatbilisicongress.com may be required
            to disclose your Personal Data if required to do so by law or in
            response to valid requests by public authorities (e.g. a court or a
            government agency).
          </Paragraph>
          <Paragraph>
            <span>Legal requirements</span>
            <br />
            wpatbilisicongress.com may disclose your Personal Data in the good
            faith belief that such action is necessary to:
          </Paragraph>
          <UlList>
            <GuideList>To comply with a legal obligation</GuideList>
            <GuideList>
              To protect and defend the rights or property of the Alliance for
              Better Mental Health
            </GuideList>
            <GuideList>
              To prevent or investigate possible wrongdoing in connection with
              the Service
            </GuideList>
            <GuideList>
              To protect the personal safety of users of the Service or the
              public
            </GuideList>
            <GuideList>To protect against legal liability</GuideList>
          </UlList>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} />{" "}
            <h4>Security of Data</h4>
          </UlTitle>
          <Paragraph>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} /> <h4>Payments</h4>
          </UlTitle>
          <Paragraph>
            We provide paid service within the Service. In that case, we use
            third-party{" "}
            <a
              href="https://www.tbcbank.ge/web/en"
              target="_blank"
              rel="noreferrer"
            >
              (JSC TBC bank)
            </a>{" "}
            service for payment processing.
            <br />
            <br />
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processor whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa or MasterCard.
            PCI-DSS requirements help ensure the secure handling of payment
            information.
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} />{" "}
            <h4>Links to Other Sites</h4>
          </UlTitle>
          <Paragraph>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party's site. We strongly advise you to review the Privacy
            Policy of every site you visit.
            <br />
            <br />
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} />{" "}
            <h4>Changes to This Privacy Policy</h4>
          </UlTitle>
          <Paragraph>
            We may update our Privacy Policy. We will notify you of any changes
            by posting the new Privacy Policy on this page.
            <br />
            <br />
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
      <ParagraphWrapper>
        <GuideWrapper>
          <UlTitle>
            <FontAwesomeIcon icon={faChevronCircleRight} />{" "}
            <h4>Changes to This Privacy Policy</h4>
          </UlTitle>
          <Paragraph>
            If you have any questions about this Privacy Policy, please contact
            us.
            <br />
            The Alliance for Better Mental Health (ABMH)
            <br />
            Address: 43, Ipolitov-Ivanov st., 0153 Tbilisi, Georgia, Georgia
            <br />
            Tel.: +995 751 73 19 55
          </Paragraph>
        </GuideWrapper>
      </ParagraphWrapper>
    </StyledContainer>
  );
};

const StyledContainer = styled(Container)`
  padding: 100px 0;
`;

const ParagraphWrapper = styled.div`
  padding: 20px 0;
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  flex-direction: column;
  gap: 15px;
`;
const ParagraphTitle = styled.h3`
  color: #000;
  font-family: "Titillium Web", sans-serif;
  font-size: 30px;
  font-weight: 700;
  text-transform: capitalize;
  /* margin-bottom: 30px; */
`;

const Paragraph = styled.p`
  font-family: "Titillium Web", sans-serif;
  font-size: 16px;
  font-weight: 500;
  color: #000;
  line-height: 1.6;
  span {
      font-weight: 600;
  }
`;

const GuideWrapper = styled.div`
  display: flex;
  justify-content: flex-start;
  align-items: flex-start;
  flex-direction: column;
  gap: 20px;
  margin-top: 30px;
`;
const UlTitle = styled.div`
  display: flex;
  justify-content: flex-start;
  align-items: baseline;
  gap: 10px;
  h4 {
    font-family: "Titillium Web", sans-serif;
    font-size: 20px;
    line-height: 1.6;
    color: #000;
    font-weight: 600;
  }
  svg {
    color: #bd1b21;
    font-size: 15px;
  }
`;

const UlList = styled.ul`
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  flex-direction: column;
  gap: 15px;
  margin-left: 20px;
`;

const GuideList = styled.li`
  font-family: "Titillium Web", sans-serif;
  font-size: 16px;
  font-weight: 500;
  line-height: 1.6;
  color: #000;
  display: flex;
  justify-content: flex-start;
  align-items: baseline;
  gap: 10px;
  &.bold {
    font-weight: 600;
  }
  &:before {
    content: "";
    display: block;
    min-width: 12px;
    min-height: 12px;
    border-radius: 50%;
    background-color: transparent;
    border: 2px solid #bd1b21;
  }
  span {
    font-weight: 700;
  }
`;

export default Policy;
